# Generated by Django 3.0.3 on 2020-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_course_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='part',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
