# Generated by Django 3.0.3 on 2020-02-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='courses',
            field=models.ManyToManyField(blank=True, to='education.Course'),
        ),
    ]
