# Generated by Django 3.0.3 on 2020-02-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_book_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.TextField(blank=True),
        ),
    ]
